// ...existing code...
const handleSubmit = async (e: React.FormEvent) => {
  e.preventDefault();
  // ...existing code for sending contact form...
  // After successful submission:
  window.scrollTo({ top: 0, behavior: 'smooth' });
  // ...existing code...
};
// ...existing code...

